apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-parcelize'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlinx-serialization'
apply plugin: 'com.google.devtools.ksp'
apply plugin: 'maven-publish'

android {
    compileSdk 35

    resourcePrefix 'panda_'

    sourceSets {
        androidTest.assets.srcDirs += files("$projectDir/schemas".toString())
    }

    defaultConfig {
        minSdk 24
        targetSdk 35

        buildConfigField "String", "PANDA_ENDPOINT_PROD", "\"https://api.panda.boosters.company/\""
        buildConfigField "String", "PANDA_ENDPOINT_STAGE", "\"https://api.panda-stage.boosters.company/\""

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            postprocessing {
                obfuscate false
                proguardFiles = ['proguard-android-optimize.txt', 'proguard-rules.pro']
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }
    testOptions {
        unitTests.all {
            useJUnitPlatform()
        }
    }
    ksp {
        arg("room.schemaLocation", "$projectDir/schemas")
    }
    buildFeatures {
        viewBinding true
        buildConfig true
    }
    namespace 'com.appsci.panda.sdk'
}

def localProperties = new Properties()
def localPropsFile = rootProject.file("local.properties")
if (localPropsFile.exists()) {
    localProperties.load(new FileInputStream(localPropsFile))
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.AppSci'
                artifactId = 'panda-sdk-android'
                version = '1.8.0'
            }
        }

        repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/Promova/panda-sdk-android")
                credentials {
                    def username = localProperties['github.actor']?: System.getenv("GPR_USER")
                    def password = localProperties['github.token']?: System.getenv("GPR_API_KEY")
                    setUsername(username)
                    setPassword(password)
                }
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])

    implementation presentationDependencies.lifecycleRuntime
    implementation presentationDependencies.fragment
    implementation presentationDependencies.fragmentKtx

    implementation supportDependencies.appCompat

    // Dagger 2
    implementation dataDependencies.dagger
    kapt dataDependencies.daggerCompiler

    // Kotlin dependencies
    implementation kotlinDependencies.kotlinStdLib
    implementation kotlinDependencies.androidKtx

    implementation dataDependencies.room
    implementation dataDependencies.roomKtx
    ksp dataDependencies.roomCompiler

    implementation dataDependencies.threeten
    implementation dataDependencies.okHttp
    implementation dataDependencies.okHttpInterceptor
    implementation dataDependencies.retrofit
    implementation dataDependencies.retrofitScalarsConverter
    implementation dataDependencies.retrofitKotlinxConverter
    implementation dataDependencies.kotlinxSerializationJson

    implementation platform('com.google.firebase:firebase-bom:33.16.0')
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-analytics'

    // Billing
    implementation dataDependencies.billingKtx
    implementation dataDependencies.billingClient

    implementation developmentDependencies.timber

    implementation coroutineDependencies.core
    implementation coroutineDependencies.android


    testImplementation testDependencies.jupiterApi
    testImplementation testDependencies.jupiterEngine
    testImplementation testDependencies.jupiterParams
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.13.3'
    testImplementation testDependencies.mockK
    testImplementation testDependencies.assertJ
    testImplementation coroutineDependencies.test

    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    androidTestImplementation androidTestDependencies.testRunner
    androidTestImplementation androidTestDependencies.espressoCore
    androidTestImplementation androidTestDependencies.supportAnnotations
    androidTestImplementation androidTestDependencies.testRoom, {
        exclude group: 'com.android.support'
    }
}
